# Generated by Django 5.0 on 2024-02-03 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kinds', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='is_actie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='is_delete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=300)),
                ('short_description', models.CharField(max_length=260)),
                ('description', models.TextField()),
                ('category', models.ManyToManyField(to='product.category')),
                ('is_actie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.is_actie')),
                ('is_delete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.is_delete')),
            ],
        ),
    ]
