# Generated by Django 5.0 on 2024-03-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('is_actie', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('short_description', models.CharField(max_length=260)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('slug', models.SlugField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='product')),
                ('category', models.ManyToManyField(to='product.productcategory')),
            ],
        ),
    ]
