# Generated by Django 5.0 on 2024-03-02 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=300)),
                ('is_actie', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('short_description', models.CharField(max_length=260)),
                ('description', models.TextField()),
            ],
        ),
    ]
